package gui;

import dao.ClienteDAO;
import javax.swing.JOptionPane;
import model.Cliente;
import gui.CadastroCliente;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class CadastroCliente2At extends javax.swing.JFrame {
    
//Cliente c = new Cliente();    
    
String nome2;
String tel2;
String email2;
String dtnasc2;
   
Cliente c= new Cliente();
ClienteDAO dao = new ClienteDAO();

    /**
     * Creates new form CadastroCliente2
     */
    public CadastroCliente2At(Cliente c) {
        initComponents();
        setSize(408,550);
//        System.out.println(c.getNome());
//        System.out.println(c.getTelefone());
//        System.out.println(c.getEmail());
//        System.out.println(c.getDt_nasc());
//        
        nome2=c.getNome();
        tel2=c.getTelefone();
        email2=c.getEmail();
        dtnasc2=c.getDt_nasc();
        
            }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        TextNum = new javax.swing.JTextField();
        TextCidade = new javax.swing.JTextField();
        TextLogr = new javax.swing.JTextField();
        TextBairro = new javax.swing.JTextField();
        TextCep = new javax.swing.JFormattedTextField();
        ComboEstado = new javax.swing.JComboBox<>();
        Logradouro = new javax.swing.JLabel();
        CEP = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        Bairro = new javax.swing.JLabel();
        Cidade = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        TextCadastro = new javax.swing.JLabel();
        Simbolo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();
        fundo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        TextNum.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(TextNum);
        TextNum.setBounds(130, 240, 190, 30);

        TextCidade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCidadeActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(TextCidade);
        TextCidade.setBounds(110, 400, 190, 30);

        TextLogr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextLogr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLogrActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(TextLogr);
        TextLogr.setBounds(170, 130, 190, 30);

        TextBairro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(TextBairro);
        TextBairro.setBounds(110, 340, 190, 30);

        try {
            TextCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInternalFrame1.getContentPane().add(TextCep);
        TextCep.setBounds(90, 190, 180, 30);

        ComboEstado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        ComboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEstadoActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(ComboEstado);
        ComboEstado.setBounds(110, 300, 80, 30);

        Logradouro.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        Logradouro.setForeground(new java.awt.Color(255, 204, 102));
        Logradouro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logradouro.setText("Logradouro:");
        jInternalFrame1.getContentPane().add(Logradouro);
        Logradouro.setBounds(10, 130, 160, 30);

        CEP.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        CEP.setForeground(new java.awt.Color(255, 204, 102));
        CEP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CEP.setText("CEP:");
        jInternalFrame1.getContentPane().add(CEP);
        CEP.setBounds(10, 190, 70, 30);

        Numero.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        Numero.setForeground(new java.awt.Color(255, 204, 102));
        Numero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Numero.setText("Número:");
        jInternalFrame1.getContentPane().add(Numero);
        Numero.setBounds(10, 240, 110, 30);

        Bairro.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        Bairro.setForeground(new java.awt.Color(255, 204, 102));
        Bairro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bairro.setText("Bairro:");
        jInternalFrame1.getContentPane().add(Bairro);
        Bairro.setBounds(10, 340, 90, 30);

        Cidade.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        Cidade.setForeground(new java.awt.Color(255, 204, 102));
        Cidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cidade.setText("Cidade:");
        jInternalFrame1.getContentPane().add(Cidade);
        Cidade.setBounds(10, 390, 100, 40);

        Estado.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        Estado.setForeground(new java.awt.Color(255, 204, 102));
        Estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Estado.setText("Estado:");
        jInternalFrame1.getContentPane().add(Estado);
        Estado.setBounds(10, 290, 90, 40);

        TextCadastro.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        TextCadastro.setForeground(new java.awt.Color(255, 204, 102));
        TextCadastro.setText("Cadastro de Cliente:");
        jInternalFrame1.getContentPane().add(TextCadastro);
        TextCadastro.setBounds(100, 20, 240, 40);

        Simbolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Simbolo.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(Simbolo);
        Simbolo.setBounds(0, 0, 100, 110);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(120, 440, 130, 30);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Fundo cadastro.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 380, 480);

        fundo.setLayout(null);
        jInternalFrame1.getContentPane().add(fundo);
        fundo.setBounds(0, 0, 370, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void TextCidadeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

//Cliente c = new Cliente();
c.setLogradouro(TextLogr.getText());
c.setBairro(TextBairro.getText());
c.setCidade(TextCidade.getText());
c.setCep(TextCep.getText());
c.setNumero(Integer.parseInt(TextNum.getText()));
c.setEstado((String)ComboEstado.getSelectedItem());
c.setNome(nome2);
c.setTelefone(tel2);
c.setEmail(email2);
c.setDt_nasc(dtnasc2);

dao.adiciona(c);
JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");


    TelaCRUDAt cad = new TelaCRUDAt();
    cad.setVisible(true);
    this.dispose();

this.dispose();
    }                                        

    private void TextLogrActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void ComboEstadoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
      //          new CadastroCliente2(c).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Bairro;
    private javax.swing.JLabel CEP;
    private javax.swing.JLabel Cidade;
    private javax.swing.JComboBox<String> ComboEstado;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Logradouro;
    private javax.swing.JLabel Numero;
    private javax.swing.JLabel Simbolo;
    private javax.swing.JTextField TextBairro;
    private javax.swing.JLabel TextCadastro;
    private javax.swing.JFormattedTextField TextCep;
    private javax.swing.JTextField TextCidade;
    private javax.swing.JTextField TextLogr;
    private javax.swing.JTextField TextNum;
    private javax.swing.JPanel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration                   
}
