package gui;

import dao.ProdutoDAO;
import javax.swing.JOptionPane;
import model.Produto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class CadastroProduto extends javax.swing.JFrame {
Produto p = new Produto();
ProdutoDAO dao = new ProdutoDAO();
    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
        setSize(448,655);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        Simbolo = new javax.swing.JLabel();
        Cadastrar = new javax.swing.JButton();
        TextEstMin = new javax.swing.JTextField();
        TextPreco = new javax.swing.JTextField();
        TextQuant = new javax.swing.JTextField();
        TextDesc = new javax.swing.JTextField();
        TextNomeProduto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        Simbolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Simbolo.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(Simbolo);
        Simbolo.setBounds(0, 0, 100, 100);

        Cadastrar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/2222.png"))); // NOI18N
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Cadastrar);
        Cadastrar.setBounds(140, 550, 140, 40);

        TextEstMin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jInternalFrame1.getContentPane().add(TextEstMin);
        TextEstMin.setBounds(220, 480, 180, 50);

        TextPreco.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jInternalFrame1.getContentPane().add(TextPreco);
        TextPreco.setBounds(220, 400, 180, 50);

        TextQuant.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jInternalFrame1.getContentPane().add(TextQuant);
        TextQuant.setBounds(220, 320, 180, 50);

        TextDesc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jInternalFrame1.getContentPane().add(TextDesc);
        TextDesc.setBounds(220, 240, 180, 50);

        TextNomeProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TextNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeProdutoActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(TextNomeProduto);
        TextNomeProduto.setBounds(220, 160, 180, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Tela cadastro PRODUTO.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 610);

        jPanel1.setLayout(null);
        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeProdutoActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed


p.setProduto(TextNomeProduto.getText());
p.setQuantidade(Integer.parseInt(TextQuant.getText()));
p.setPreco(Float.parseFloat(TextPreco.getText()));
p.setEstMin(Integer.parseInt(TextEstMin.getText()));
p.setDescricao(TextDesc.getText());
dao.adiciona(p);
JOptionPane.showMessageDialog(null,"Produto cadastrado com sucesso!");
TelaCRUD2 crud = new TelaCRUD2();
crud.setVisible(true);
this.dispose();
    }//GEN-LAST:event_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JLabel Simbolo;
    private javax.swing.JTextField TextDesc;
    private javax.swing.JTextField TextEstMin;
    private javax.swing.JTextField TextNomeProduto;
    private javax.swing.JTextField TextPreco;
    private javax.swing.JTextField TextQuant;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
