
package gui;

import dao.NFDAO;
import javax.swing.JOptionPane;
import model.Cliente;
import model.NF;
import model.Venda;

public class NotaFiscal extends javax.swing.JFrame {
 NFDAO nfd = new NFDAO();
 Venda v  = new Venda();
 Cliente c = new Cliente();
 NF nf = new NF();
 int codV2;
 
    public NotaFiscal(int codV) {
        initComponents();
     codV2=codV;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoForma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CampoTotal = new javax.swing.JTextField();
        CampoData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                Add(evt);
            }
        });

        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Simbolo1.png"))); // NOI18N
        jInternalFrame2.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 100, 100);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Nota Fiscal:");
        jInternalFrame2.getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 0, 130, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Data da Venda:");
        jInternalFrame2.getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 40, 130, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Cliente:");
        jInternalFrame2.getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 63, 80, 22);

        CampoCliente.setEditable(false);
        CampoCliente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jInternalFrame2.getContentPane().add(CampoCliente);
        CampoCliente.setBounds(100, 90, 240, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Forma de Pagamento: ");
        jInternalFrame2.getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 250, 180, 20);

        CampoForma.setEditable(false);
        CampoForma.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jInternalFrame2.getContentPane().add(CampoForma);
        CampoForma.setBounds(220, 250, 100, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Total: ");
        jInternalFrame2.getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 280, 60, 20);

        CampoTotal.setEditable(false);
        CampoTotal.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jInternalFrame2.getContentPane().add(CampoTotal);
        CampoTotal.setBounds(340, 280, 80, 20);

        CampoData.setEditable(false);
        CampoData.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jInternalFrame2.getContentPane().add(CampoData);
        CampoData.setBounds(360, 40, 90, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jInternalFrame2.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 420, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Add

        nfd.add(nf,codV2);
        
        CampoCliente.setText(nf.getNome());
        CampoData.setText(nf.getDt_venda());
        CampoForma.setText(nf.getPagamento());
        CampoTotal.setText(String.valueOf(nf.getValTot()));
        
         String sql="select i.cod_item, p.produto,i.quant_item, p.preco,"
                 + "p.preco*i.quant_item as Total from produto p,"
                    + " item_venda i ";
                 sql=sql + " where p.cod_prod=i.cod_prod and i.cod_venda=" 
                    + codV2;
                sql= sql + " order by i.cod_item";
                
                
                jTable1=nfd.MontaLista(sql, jTable1); 
             
             
        
    }//GEN-LAST:event_Add

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCliente;
    private javax.swing.JTextField CampoData;
    private javax.swing.JTextField CampoForma;
    private javax.swing.JTextField CampoTotal;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
