package gui;

import connection.ConnectionFactory;
import dao.ClienteDAO;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class TelaCRUD extends javax.swing.JFrame {

ClienteDAO cdao = new ClienteDAO();
    /**
     * Creates new form TelaCRUD
     */
    public TelaCRUD() {
        initComponents();
        setSize(395,470);
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        Simbolo = new javax.swing.JLabel();
        IncluirCliente = new javax.swing.JButton();
        ConsultarCliente = new javax.swing.JButton();
        AlterarCliente = new javax.swing.JButton();
        DeletarCliente = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);
        jInternalFrame1.getContentPane().add(Simbolo);
        Simbolo.setBounds(0, 10, 100, 100);

        IncluirCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        IncluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/IncluirCliente.png"))); // NOI18N
        IncluirCliente.setText("<html>Incluir Informações<p> do Cliente</html>");
        IncluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirClienteActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(IncluirCliente);
        IncluirCliente.setBounds(100, 70, 180, 50);

        ConsultarCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/LerCliente.png"))); // NOI18N
        ConsultarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarClienteActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(ConsultarCliente);
        ConsultarCliente.setBounds(100, 140, 180, 50);

        AlterarCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/AlterarCliente.png"))); // NOI18N
        AlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarClienteActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(AlterarCliente);
        AlterarCliente.setBounds(100, 210, 180, 50);

        DeletarCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DeletarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/DeletarCliente.png"))); // NOI18N
        DeletarCliente.setToolTipText("");
        DeletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarClienteActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(DeletarCliente);
        DeletarCliente.setBounds(100, 280, 180, 50);

        Sair.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/PARAPAPAPA.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Sair);
        Sair.setBounds(220, 350, 110, 40);

        Voltar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/TAFICANDOAPERTADO.png"))); // NOI18N
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Voltar);
        Voltar.setBounds(50, 350, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/TelaCRUD.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 380, 420);

        jPanel1.setLayout(null);
        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 400);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 420, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IncluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirClienteActionPerformed
       CadastroCliente cadastro = new CadastroCliente();
       cadastro.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_IncluirClienteActionPerformed

    private void ConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarClienteActionPerformed

  String id;
  id=JOptionPane.showInputDialog("Buscar código do cliente:");
  
  cdao.buscarCliente(id);
        
    }//GEN-LAST:event_ConsultarClienteActionPerformed

    private void AlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarClienteActionPerformed
       String escolha;
       String cod_cliente;
       String nome=null;
       String dt_nasc=null;
       String telefone=null;
       String email=null;
       String logradouro=null;
       String cep=null;
       int num=0;
       String bairro=null;
       String cidade=null;
       String estado=null;
       
       String resposta="";
      
//        resposta=JOptionPane.showInputDialog("Deseja alterar algo?");
       
        while (!resposta.equals("não")){
            resposta=JOptionPane.showInputDialog("Deseja alterar algo?\n(sim/não)");
            if(resposta.equals("não")){
                JOptionPane.showMessageDialog(null,"OK, nada será alterado, então...");
                break;
            }
            cod_cliente=JOptionPane.showInputDialog("Qual o Código do cliente que você deseja alterar?  ");
            escolha=JOptionPane.showInputDialog("O que você deseja alterar?\nOpções: nome, data de nascimento, telefone\nemail"
                    + ", logradouro, CEP, número\n bairro, cidade, estado");
                switch (escolha){
                    case "nome":
                       cdao.editarClienteNome(cod_cliente,nome);
                       break;
                    case "data de nascimento":
                       cdao.editarClienteDtNasc(cod_cliente,dt_nasc);
                       break;
                    case "telefone":
                       cdao.editarClienteTel(cod_cliente,telefone);
                       break;
                    case "email":
                       cdao.editarClienteEmail(cod_cliente,email);
                       break;
                    case "logradouro":
                       cdao.editarClienteLogradouro(cod_cliente, logradouro);
                       break;
                    case "CEP":
                       cdao.editarClienteCep(cod_cliente, cep);
                        break;
                    case "número":
                       cdao.editarClienteNum(cod_cliente, num);
                        break;
                    case "bairro":
                        cdao.editarClienteBairro(cod_cliente, bairro);
                        break;
                    case "cidade":
                        cdao.editarClienteCidade(cod_cliente, cidade);
                        break;
                    case "estado":
                        cdao.editarClienteEstado(cod_cliente, estado);
                        break;
                        
                       default:
                           JOptionPane.showMessageDialog(null, "Erro");

            }
       }
    }//GEN-LAST:event_AlterarClienteActionPerformed

    private void DeletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarClienteActionPerformed

        String cod_cliente;
      cod_cliente=JOptionPane.showInputDialog("Diga qual o código do cliente que deseja excluir:");
      
      cdao.deletarCliente(cod_cliente);
    }//GEN-LAST:event_DeletarClienteActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
JOptionPane.showMessageDialog(null, "Obrigado por usar o programa! Volte sempre!");
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SairActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
  TelaGerente volt = new TelaGerente();
  volt.setVisible(true);
  this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarCliente;
    private javax.swing.JButton ConsultarCliente;
    private javax.swing.JButton DeletarCliente;
    private javax.swing.JButton IncluirCliente;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel Simbolo;
    private javax.swing.JButton Voltar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
