package gui;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class TelaAtendente extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtendente
     */
    public TelaAtendente() {
        initComponents();
        setSize(604,380);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        Simbolo = new javax.swing.JLabel();
        CadastrarCliente = new javax.swing.JButton();
        EmitirCuponsVenda = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);
        jInternalFrame1.getContentPane().add(Simbolo);
        Simbolo.setBounds(0, 0, 100, 100);

        CadastrarCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Manter Cliente.png"))); // NOI18N
        CadastrarCliente.setToolTipText("");
        CadastrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarClienteActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(CadastrarCliente);
        CadastrarCliente.setBounds(370, 180, 160, 50);

        EmitirCuponsVenda.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        EmitirCuponsVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/efetuarVenda.png"))); // NOI18N
        EmitirCuponsVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmitirCuponsVendaActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(EmitirCuponsVenda);
        EmitirCuponsVenda.setBounds(50, 180, 160, 50);

        sair.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/SAIUDO.png"))); // NOI18N
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(sair);
        sair.setBounds(230, 270, 90, 30);

        jPanel1.setLayout(null);
        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Tela atendente.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarClienteActionPerformed
        TelaCRUDAt crud = new TelaCRUDAt();
        crud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CadastrarClienteActionPerformed

    private void EmitirCuponsVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmitirCuponsVendaActionPerformed
        TelaVenda venda = new TelaVenda();
        venda.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_EmitirCuponsVendaActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
JOptionPane.showMessageDialog(null, "Obrigado por usar o programa, volte sempre!");
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarCliente;
    private javax.swing.JButton EmitirCuponsVenda;
    private javax.swing.JLabel Simbolo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
